title: Funky Trees Docs
description: Funky Trees Language Documentation
theme: just-the-docs
baseurl: ""
url: "https://snowflake0s.github.io/"
favicon_ico: "/assets/images/favicon.ico"
color_scheme: dark